# The name of the final artifact
BINARY_NAME=bootstrap

# Default target executed when no arguments are given to make
all: build

# Copy source files to the build directory
build:
	cp -R * $(ARTIFACTS_DIR)

# Clean up the build directory
clean:
	rm -rf $(ARTIFACTS_DIR)/*